### ISSUE TITLE
Postgres errors in log file during benchmark

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store-benchmarks#7]
There are many errors in the postgres server log (`docker-compose logs -f`) during benchmark.

**Comment by sandrokeil** [comment]
These are the errors with current master branch.
[logs.txt](https://github.com/prooph/event-store-benchmarks/files/1369586/logs.txt)

**Comment by codeliner** [comment]
I've put a `throw $e` here: https://github.com/prooph/pdo-event-store/blob/master/src/Projection/PdoEventStoreProjector.php#L483

That resulted in:

```
Projection 140591524575976 started
A stream with name post-06d31f03-d3f1-4940-87ea-1b26e5f9fc8e could not be found
#0 /app/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(481): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1)
#2 /app/src/CategoryProjector.php(52): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\CategoryProjector->run()
#4 {main}A stream with name blog-371a6782-c1cd-48c4-b82f-3e3a61fa026b could not be found
#0 /app/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(481): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1)
#2 /app/src/CategoryProjector.php(52): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\CategoryProjector->run()
#4 {main}A stream with name user-5df3d91e-2891-4cdc-b1b3-88a97f74e9dc could not be found
#0 /app/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(481): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1)
#2 /app/src/CategoryProjector.php(52): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\CategoryProjector->run()
#4 {main}A stream with name comment-652e0d69-8cd8-4681-8902-d92ad1ad65af could not be found
#0 /app/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(481): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1)
#2 /app/src/CategoryProjector.php(52): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\CategoryProjector->run()
#4 {main}A stream with name todo-706556b2-d3ef-4fbb-a34b-dce60fe7f305 could not be found
#0 /app/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(481): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1)
#2 /app/src/CategoryProjector.php(52): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\CategoryProjector->run()
#4 {main}A stream with name comment-33cae6a6-638b-47b1-8eb9-69ebc2c39438 could not be found
#0 /app/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(481): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1)
#2 /app/src/AllProjector.php(48): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\AllProjector->run()
#4 {main}Writer 140591638854376 wrote 250 events
Writer 140591638854376 used 12.298284053802 seconds, avg 20.328039172481 events/second
Writer 140591625464552 wrote 250 events
Writer 140591625464552 used 12.285501003265 seconds, avg 20.349190475305 events/second
Writer 140591638371048 wrote 250 events
```
